# Generated by Django 5.2.7 on 2025-12-18 18:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Declaration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('declaration_number', models.CharField(blank=True, max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pdf_url', models.URLField(blank=True, null=True)),
                ('praxis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='declarations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Konformitätserklärung',
                'verbose_name_plural': 'Konformitätserklärungen',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeclarationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_number', models.IntegerField(default=1)),
                ('material', models.CharField(help_text='Malzeme adı', max_length=200)),
                ('device', models.CharField(help_text='Cihaz/Ürün adı', max_length=200)),
                ('manufacturer', models.CharField(help_text='Üretici firma', max_length=200)),
                ('ce_number', models.CharField(help_text='CE sertifika numarası', max_length=100)),
                ('declaration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='declarations.declaration')),
            ],
            options={
                'verbose_name': 'Beyan Satırı',
                'verbose_name_plural': 'Beyan Satırları',
                'ordering': ['line_number'],
            },
        ),
    ]
