# Generated by Django 5.2.7 on 2025-12-18 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('declarations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ürün kombinasyon adı', max_length=200, unique=True)),
                ('material', models.CharField(help_text='Malzeme', max_length=200)),
                ('device', models.CharField(help_text='Cihaz/Ürün', max_length=200)),
                ('manufacturer', models.CharField(help_text='Üretici', max_length=200)),
                ('ce_number', models.CharField(help_text='CE Numarası', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Material Product',
                'verbose_name_plural': 'Material Products',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='declarationitem',
            name='material_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='declarations.materialproduct'),
        ),
    ]
