# Generated by Django 5.2.7

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('declarations', '0002_materialproduct_declarationitem_material_product'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HerstellerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firma_name', models.CharField(max_length=200, verbose_name='Firma Adı')),
                ('strasse', models.CharField(max_length=200, verbose_name='Straße')),
                ('plz', models.CharField(max_length=10, verbose_name='PLZ')),
                ('ort', models.CharField(max_length=100, verbose_name='Ort')),
                ('telefon', models.CharField(max_length=50, verbose_name='Telefon')),
                ('email', models.EmailField(max_length=254, verbose_name='E-Mail')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hersteller_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Hersteller Profil',
                'verbose_name_plural': 'Hersteller Profile',
            },
        ),
        migrations.AddField(
            model_name='declaration',
            name='herstellungsdatum',
            field=models.DateField(default='2025-01-01', verbose_name='Herstellungsdatum'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='declaration',
            name='patient_name',
            field=models.CharField(default='', max_length=200, verbose_name='Patientenname'),
            preserve_default=False,
        ),
    ]
