# Generated by Django 5.2.7

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('declarations', '0003_herstellerprofile_declaration_herstellungsdatum_and_more'),
    ]

    operations = [
        # DeclarationItem field updates
        migrations.RenameField(
            model_name='declarationitem',
            old_name='manufacturer',
            new_name='firma',
        ),
        migrations.RemoveField(
            model_name='declarationitem',
            name='device',
        ),
        migrations.RemoveField(
            model_name='declarationitem',
            name='ce_number',
        ),
        migrations.AddField(
            model_name='declarationitem',
            name='bestandteile',
            field=models.CharField(default='', help_text='İçerik/Bileşenler', max_length=500, verbose_name='Bestandteile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='declarationitem',
            name='material_lot_no',
            field=models.CharField(default='', help_text='Lot numarası', max_length=100, verbose_name='Material Lot No.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='declarationitem',
            name='ce_status',
            field=models.CharField(default='Ja', help_text='CE durumu', max_length=10, verbose_name='CE'),
        ),
        migrations.AddField(
            model_name='declarationitem',
            name='device_identification',
            field=models.CharField(blank=True, default='', help_text='Ürün tanımı', max_length=200, verbose_name='Produkt'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='declarationitem',
            name='material',
            field=models.CharField(help_text='Malzeme adı', max_length=200, verbose_name='Material'),
        ),

        # MaterialProduct field updates
        migrations.RenameField(
            model_name='materialproduct',
            old_name='manufacturer',
            new_name='firma',
        ),
        migrations.RemoveField(
            model_name='materialproduct',
            name='device',
        ),
        migrations.RemoveField(
            model_name='materialproduct',
            name='ce_number',
        ),
        migrations.AddField(
            model_name='materialproduct',
            name='bestandteile',
            field=models.CharField(default='', help_text='İçerik/Bileşenler', max_length=500, verbose_name='Bestandteile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='materialproduct',
            name='material_lot_no',
            field=models.CharField(default='', help_text='Lot numarası', max_length=100, verbose_name='Material Lot No.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='materialproduct',
            name='ce_status',
            field=models.CharField(default='Ja', help_text='CE durumu', max_length=10, verbose_name='CE'),
        ),
        migrations.AddField(
            model_name='materialproduct',
            name='device_identification',
            field=models.CharField(blank=True, default='', help_text='Ürün tanımı', max_length=200, verbose_name='Produkt'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='materialproduct',
            name='material',
            field=models.CharField(help_text='Malzeme', max_length=200, verbose_name='Material'),
        ),
    ]
