# Generated by Django 5.2.7 on 2025-12-19 10:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('declarations', '0003_herstellerprofile_declaration_herstellungsdatum_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='herstellerprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='herstellerprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
