# Generated by Django 5.2.7 on 2025-12-19 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('declarations', '0004_herstellerprofile_created_at_and_more'),
        ('declarations', '0004_update_declarationitem_materialproduct_fields'),
    ]

    operations = [
    ]
