# Generated by Django 5.2.7 on 2025-12-19 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('declarations', '0005_merge_20251219_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='declaration',
            name='auftragsnummer',
            field=models.CharField(blank=True, max_length=100, verbose_name='Auftragsnummer'),
        ),
        migrations.AddField(
            model_name='herstellerprofile',
            name='verordnender_arzt',
            field=models.CharField(blank=True, max_length=200, verbose_name='Verordnender Arzt'),
        ),
        migrations.AlterField(
            model_name='declarationitem',
            name='firma',
            field=models.CharField(help_text='Üretici firma', max_length=200, verbose_name='Hersteller'),
        ),
        migrations.AlterField(
            model_name='materialproduct',
            name='firma',
            field=models.CharField(help_text='Üretici firma', max_length=200, verbose_name='Hersteller'),
        ),
    ]
