# Generated by Django 5.2.7 on 2025-12-19 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('declarations', '0006_declaration_auftragsnummer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_number', models.IntegerField(default=1)),
                ('produktbezeichnung_arbeit', models.CharField(max_length=200, verbose_name='Produktbezeichnung / Arbeit')),
                ('zahnnummer', models.CharField(blank=True, max_length=100, verbose_name='Zahnnummer')),
                ('zahnfarbe', models.CharField(blank=True, max_length=100, verbose_name='Zahnfarbe')),
                ('declaration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_works', to='declarations.declaration')),
            ],
            options={
                'verbose_name': 'Produktbezeichnung',
                'verbose_name_plural': 'Produktbezeichnungen',
                'ordering': ['line_number'],
            },
        ),
    ]
