# Generated by Django 4.2.11 on 2025-12-20 15:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('declarations', '0008_materialproduct_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchiveDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titel')),
                ('description', models.TextField(blank=True, verbose_name='Beschreibung')),
                ('drive_file_id', models.CharField(blank=True, max_length=200)),
                ('drive_url', models.URLField(blank=True)),
                ('file_name', models.CharField(max_length=200)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('category', models.CharField(choices=[('invoice', 'Rechnung'), ('declaration', 'Erklärung'), ('certificate', 'Zertifikat'), ('contract', 'Vertrag'), ('other', 'Sonstiges')], default='other', max_length=20, verbose_name='Kategorie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archive_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Archiv Dokument',
                'verbose_name_plural': 'Archiv Dokumente',
                'ordering': ['-upload_date'],
            },
        ),
    ]
