# Generated by Django 4.2.11 on 2025-12-21 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('declarations', '0009_archivedocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivedocument',
            name='custom_category',
            field=models.CharField(blank=True, max_length=100, verbose_name='Özel Kategori'),
        ),
    ]
