# Generated by Django 4.2.11 on 2025-12-21 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('declarations', '0010_archivedocument_custom_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivedocument',
            name='document_date',
            field=models.DateField(blank=True, null=True, verbose_name='Dokumentdatum'),
        ),
    ]
