# Generated by Django 4.2.11 on 2025-12-22 10:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('declarations', '0011_archivedocument_document_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='declaration',
            name='declaration_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='declaration',
            unique_together={('praxis', 'declaration_number')},
        ),
    ]
