# Generated by Django 5.2.7 on 2026-01-19 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('declarations', '0012_alter_declaration_declaration_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='herstellerprofile',
            name='email_verified',
            field=models.BooleanField(default=False, verbose_name='E-Mail bestätigt'),
        ),
        migrations.AddField(
            model_name='herstellerprofile',
            name='profile_completed',
            field=models.BooleanField(default=False, verbose_name='Profil vollständig'),
        ),
        migrations.AddField(
            model_name='herstellerprofile',
            name='token_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='herstellerprofile',
            name='verification_token',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='herstellerprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='E-Mail'),
        ),
        migrations.AlterField(
            model_name='herstellerprofile',
            name='firma_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Firma Adı'),
        ),
        migrations.AlterField(
            model_name='herstellerprofile',
            name='ort',
            field=models.CharField(blank=True, max_length=100, verbose_name='Ort'),
        ),
        migrations.AlterField(
            model_name='herstellerprofile',
            name='plz',
            field=models.CharField(blank=True, max_length=10, verbose_name='PLZ'),
        ),
        migrations.AlterField(
            model_name='herstellerprofile',
            name='strasse',
            field=models.CharField(blank=True, max_length=200, verbose_name='Straße'),
        ),
        migrations.AlterField(
            model_name='herstellerprofile',
            name='telefon',
            field=models.CharField(blank=True, max_length=50, verbose_name='Telefon'),
        ),
    ]
